@startuml
left to right direction
actor NhanVien #line:A80036;
usecase QuanLyTaiKhoanKhachHang #Wheat;line:A80036;
usecase DangNhap #Wheat;line:A80036;
usecase CapNhatTrangThai #Wheat;line:A80036;

NhanVien  --> QuanLyTaiKhoanKhachHang #line:A80036 : \t\t\t\t
QuanLyTaiKhoanKhachHang  .left.>  DangNhap #line:A80036 : \n\n\n\n <<include>> \n\n\n\n
QuanLyTaiKhoanKhachHang  <.down.  CapNhatTrangThai #line:A80036 : \t\t  <<extend>> \t\t
@endum