@startuml
left to right direction
actor KhachHang #line:A80036;
usecase XuLyDatHang #Wheat;line:A80036;
usecase DatHang #Wheat;line:A80036;
usecase TraCuuDonHang #Wheat;line:A80036;
usecase HuyDonHang #Wheat;line:A80036;

KhachHang  --> XuLyDatHang #line:A80036 : \t\t\t\t
XuLyDatHang  <.left.  DatHang #line:A80036 : \n\n\n\n<<extend>>\n\n\n\n
XuLyDatHang  <.down.  TraCuuDonHang #line:A80036 : \t\t <<extend>> \t\t
XuLyDatHang  <.right.  HuyDonHang #line:A80036 : \n\n\n\n<<extend>>\n\n\n\n
@endum