@startuml

skinparam sequence {

LifeLineBorderColor #A80036

}


skinparam {
Participant underline
ArrowColor  #A80036

ActorBorderColor #A80036
ActorFontStyle bold


BoundaryFontStyle bold
BoundaryBackgroundColor #Bisque

ControlFontStyle bold
ControlBackgroundColor #Bisque

ControlFontStyle bold
ControlBackgroundColor #Bisque

EntityFontStyle bold
EntityBackgroundColor #Bisque
}


actor Admin 
boundary    QuanLySanPhamUI
control     QuanLySanPhamController
entity      Product
boundary    CSDL


Admin ->> QuanLySanPhamUI : 1: Chon san pham can cap nhat()
activate Admin
activate QuanLySanPhamUI
deactivate Admin
deactivate QuanLySanPhamUI

Admin ->> QuanLySanPhamUI : 2: Nhan nut cap nhat()
activate Admin
activate QuanLySanPhamUI
deactivate Admin
deactivate QuanLySanPhamUI

QuanLySanPhamUI ->> QuanLySanPhamUI  : 3: Hien thi form cap nhat()
activate QuanLySanPhamUI
deactivate QuanLySanPhamUI



Admin ->> QuanLySanPhamUI  : 4: Nhap thong tin san pham()
activate Admin
activate QuanLySanPhamUI
deactivate Admin
deactivate QuanLySanPhamUI

Admin ->> QuanLySanPhamUI  : 5: Nhan nut cap nhat san pham()
activate Admin
activate QuanLySanPhamUI
deactivate Admin
deactivate QuanLySanPhamUI

QuanLySanPhamUI ->> QuanLySanPhamController  : 6: Kiem tra thong tin san pham()
activate QuanLySanPhamUI
activate QuanLySanPhamController
deactivate QuanLySanPhamUI
deactivate QuanLySanPhamController

Product <<- QuanLySanPhamController : 7: Cap nhat san pham()
activate QuanLySanPhamController
activate Product
deactivate QuanLySanPhamController
deactivate Product

QuanLySanPhamController ->> CSDL : 8: Cap nhat bang product()
activate QuanLySanPhamController
activate CSDL
deactivate QuanLySanPhamController
deactivate CSDL



QuanLySanPhamController ->> QuanLySanPhamUI : 9: Hien thi thong bao()
activate QuanLySanPhamController
activate QuanLySanPhamUI
deactivate QuanLySanPhamController
deactivate QuanLySanPhamUI



@enduml
