@startuml

skinparam sequence {

LifeLineBorderColor #A80036

}


skinparam {
Participant underline
ArrowColor  #A80036

ActorBorderColor #A80036
ActorFontStyle bold


BoundaryFontStyle bold
BoundaryBackgroundColor #Bisque

ControlFontStyle bold
ControlBackgroundColor #Bisque

ControlFontStyle bold
ControlBackgroundColor #Bisque

EntityFontStyle bold
EntityBackgroundColor #Bisque
}


actor Admin 
boundary    QuanLyBlogUI
control     QuanLyBlogController
entity      Blog
boundary    CSDL


Admin ->> QuanLyBlogUI : 1: Nhan nut them()
activate Admin
activate QuanLyBlogUI
deactivate Admin
deactivate QuanLyBlogUI

QuanLyBlogUI ->> QuanLyBlogUI  : 2: Hien thi form them blog()
activate QuanLyBlogUI
deactivate QuanLyBlogUI



Admin ->> QuanLyBlogUI  : 3: Nhap thong tin blog()
activate Admin
activate QuanLyBlogUI
deactivate Admin
deactivate QuanLyBlogUI

Admin ->> QuanLyBlogUI  : 4: Nhan nut them blog()
activate Admin
activate QuanLyBlogUI
deactivate Admin
deactivate QuanLyBlogUI

QuanLyBlogUI ->> QuanLyBlogController  : 5: Kiem tra thong tin blog()
activate QuanLyBlogUI
activate QuanLyBlogController
deactivate QuanLyBlogUI
deactivate QuanLyBlogController

Blog <<- QuanLyBlogController : 6: Them blog()
activate QuanLyBlogController
activate Blog
deactivate QuanLyBlogController
deactivate Blog

QuanLyBlogController ->> CSDL : 7: Cap nhat bang blog()
activate QuanLyBlogController
activate CSDL
deactivate QuanLyBlogController
deactivate CSDL



QuanLyBlogController ->> QuanLyBlogUI : 8: Hien thi thong bao()
activate QuanLyBlogController
activate QuanLyBlogUI
deactivate QuanLyBlogController
deactivate QuanLyBlogUI



@enduml
